# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kdesu': '@stable'
    'frameworks/ktextwidgets': '@stable'
