.\" Automatically generated by Pod::Man v1.37, Pod::Parser v1.32
.\"
.\" Standard preamble:
.\" ========================================================================
.de Sh \" Subsection heading
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.\" Set up some character translations and predefined strings.  \*(-- will
.\" give an unbreakable dash, \*(PI will give pi, \*(L" will give a left
.\" double quote, and \*(R" will give a right double quote.  \*(C+ will
.\" give a nicer C++.  Capital omega is used to do unbreakable dashes and
.\" therefore won't be available.  \*(C` and \*(C' expand to `' in nroff,
.\" nothing in troff, for use with C<>.
.tr \(*W-
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.ie n \{\
.    ds -- \(*W-
.    ds PI pi
.    if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.    if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\"  diablo 12 pitch
.    ds L" ""
.    ds R" ""
.    ds C` ""
.    ds C' ""
'br\}
.el\{\
.    ds -- \|\(em\|
.    ds PI \(*p
.    ds L" ``
.    ds R" ''
'br\}
.\"
.\" If the F register is turned on, we'll generate index entries on stderr for
.\" titles (.TH), headers (.SH), subsections (.Sh), items (.Ip), and index
.\" entries marked with X<> in POD.  Of course, you'll have to process the
.\" output yourself in some meaningful fashion.
.if \nF \{\
.    de IX
.    tm Index:\\$1\t\\n%\t"\\$2"
..
.    nr % 0
.    rr F
.\}
.\"
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.hy 0
.if n .na
.\"
.\" Accent mark definitions (@(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2).
.\" Fear.  Run.  Save yourself.  No user-serviceable parts.
.    \" fudge factors for nroff and troff
.if n \{\
.    ds #H 0
.    ds #V .8m
.    ds #F .3m
.    ds #[ \f1
.    ds #] \fP
.\}
.if t \{\
.    ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.    ds #V .6m
.    ds #F 0
.    ds #[ \&
.    ds #] \&
.\}
.    \" simple accents for nroff and troff
.if n \{\
.    ds ' \&
.    ds ` \&
.    ds ^ \&
.    ds , \&
.    ds ~ ~
.    ds /
.\}
.if t \{\
.    ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.    ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.    ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.    ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.    ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.    ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.\}
.    \" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.    \" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.    \" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.    ds : e
.    ds 8 ss
.    ds o a
.    ds d- d\h'-1'\(ga
.    ds D- D\h'-1'\(hy
.    ds th \o'bp'
.    ds Th \o'LP'
.    ds ae ae
.    ds Ae AE
.\}
.rm #[ #] #H #V #F C
.\" ========================================================================
.\"
.IX Title "CERVISIA 1"
.TH CERVISIA 1 "2007-04-29" "2.4.0" "Cervisia"
.SH "NAME"
Cervisia \- Graphical CVS frontend
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBcervisia\fR
         [\ \fB\-\-display\fR\ \fIdisplay\fR\ ]
         [\ \fB\-\-caption\fR\ \fIcaption\fR\ ]
         [\ \fB\-\-icon\fR\ \fIicon\fR\ ]
         [\ \fB\-\-miniicon\fR\ \fIminiicon\fR\ ]
         [\ \fB\-\-config\fR\ \fIfilename\fR\ ]
         [\ \fB\-\-dcopserver\fR\ \fIserver\fR\ ]
         [\ \fB\-\-nocrashhandler\fR\ ]
         [\ \fB\-\-waitforwm\fR\ ]
         [\ \fB\-\-style\fR\ \fIstyle\fR\ ]
         [\ \fB\-\-geometry\fR\ \fIgeometry\fR\ ]
         [\ \fB\-\-resolve\fR\ \fIfilename\fR\ ]
         [\ \fB\-\-log\fR\ \fIfilename\fR\ ]
         [\ \fB\-\-annotate\fR\ \fIfilename\fR\ ]
         [\ \fIdirectory\fR\ ]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
Cervisia is a graphical user interface for the Concurrent Versions
System. It is based on the \s-1KDE\s0 libraries and therefore shares 
their Look'n'Feel, configuration and help system.
.SH "OPTIONS"
.IX Header "OPTIONS"
Cervisia accepts the following options:
.IP "\fIdirectory\fR" 4
.IX Item "directory"
Tells Cervisia to open the sandbox in \fIdirectory\fR at startup
.IP "\fB\-\-resolve\fR \fIfilename\fR" 4
.IX Item "--resolve filename"
Shows a resolve dialog for the given file
.IP "\fB\-\-log\fR \fIfilename\fR" 4
.IX Item "--log filename"
Shows a log dialog for the given file
.IP "\fB\-\-annotate\fR \fIfilename\fR" 4
.IX Item "--annotate filename"
Shows a annotation dialog for the given file
.IP "\fB\-\-caption\fR \fIcaption\fR" 4
.IX Item "--caption caption"
Sets the caption, i. e. what is shown in the title bar
.IP "\fB\-\-icon\fR \fIicon\fR" 4
.IX Item "--icon icon"
Sets the program's icon (used by window managers and panels)
.IP "\fB\-\-miniicon\fR \fIminiicon\fR" 4
.IX Item "--miniicon miniicon"
Sets the program's mini icon (used by window managers and panels)
.IP "\fB\-\-config\fR \fIfilename\fR" 4
.IX Item "--config filename"
Uses the given file for the configuration
.IP "\fB\-\-dcopserver\fR \fIserver\fR" 4
.IX Item "--dcopserver server"
Sets the dcopserver the program should use
.IP "\fB\-\-nocrashhandler\fR" 4
.IX Item "--nocrashhandler"
Disables the crash handler. Use this to get core dumps
.IP "\fB\-\-waitforwm\fR" 4
.IX Item "--waitforwm"
Waits for a \s-1WM_NET\s0 compatible windowmanager
.IP "\fB\-\-style\fR \fIstyle\fR" 4
.IX Item "--style style"
Sets the application \s-1GUI\s0 style
.IP "\fB\-\-geometry\fR \fIgeometry\fR" 4
.IX Item "--geometry geometry"
Sets the geometry of the main window
.SH "FILES"
.IX Header "FILES"
\&\fI_KDECONFDIR_/cervisiarc\fR \- global configuration file
.Sp
\&\fI$HOME/.kde/share/config/cervisiarc\fR \- user-specific configuration file
.SH "SEE ALSO"
.IX Header "SEE ALSO"
\&\fI_KDEHTMLDIR_/en/cervisia/index.html\fR
.Sp
\&\fIcvs\fR\|(1)
.Sp
\&\fIhttp://cervisia.kde.org/\fR
.SH "AUTHOR"
.IX Header "AUTHOR"
Cervisia was originally developed by Bernd Gehrmann and is now maintained by
Christian Loose <christian.loose@kdemail.net>.
.SH "REPORTING BUGS"
.IX Header "REPORTING BUGS"
Report bugs at http://bugs.kde.org.
